# Generated by Django 5.1.6 on 2025-04-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamBienMQ2',
            fields=[
                ('ma_cam_bien', models.BigAutoField(primary_key=True, serialize=False)),
                ('gia_tri', models.FloatField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheTuLog',
            fields=[
                ('ma_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_rfid', models.CharField(max_length=255)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(default='Đã đọc', max_length=50)),
                ('sinh_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sinhvien')),
            ],
        ),
    ]
