# Generated by Django 5.1.6 on 2025-04-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDoXe',
            fields=[
                ('ma_bai', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_bai', models.CharField(max_length=255)),
                ('vi_tri', models.CharField(max_length=255)),
                ('suc_chua', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('ma_khu_vuc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_khu_vuc', models.CharField(max_length=255)),
                ('suc_chua', models.IntegerField()),
                ('bai_do_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.baidoxe')),
            ],
        ),
    ]
