# Generated by Django 5.1.6 on 2025-04-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('ma_sv', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mat_khau', models.CharField(default='cntt123', max_length=255)),
                ('ho_ten', models.CharField(max_length=255)),
                ('id_rfid', models.CharField(max_length=255, unique=True)),
                ('so_tien_hien_co', models.FloatField(default=0)),
                ('trang_thai', models.CharField(default='Chưa đỗ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuThanhToan',
            fields=[
                ('ma_thanh_toan', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_tien', models.FloatField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuRaVao',
            fields=[
                ('ma_lich_su', models.BigAutoField(primary_key=True, serialize=False)),
                ('bien_so_xe', models.CharField(max_length=50)),
                ('thoi_gian_vao', models.DateTimeField()),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(max_length=50)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuNapTien',
            fields=[
                ('ma_nap_tien', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_tien', models.FloatField()),
                ('thoi_gian_nap', models.DateTimeField(auto_now_add=True)),
                ('phuong_thuc', models.CharField(max_length=255)),
                ('ma_giao_dich', models.CharField(max_length=255, unique=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sinhvien')),
            ],
        ),
    ]
